== Библиография
[#1]
<1> Недяк С.П., Шаропин Ю.Б. Лабораторный практикум по микроконтроллерам семейства Cortex-M:
Методическое пособие по проведению работ на отладочных платах фирмы "Миландр"- Томск. гос. ун-т
систем упр. и радиоэлектроники, 2017. - 110 с.
[#2]
<2> Волков В.Л. Программное обеспечение измерительных процессов. Учебное пособие для студентов
технических специальностей дневной, заочной, и заочной форм обучения. /АПИ НГТУ. Арзамас,
2008 – 120 с.
[#3]
<3> Руководство по оформлению кода на С++ Стэнфордского университета:
http://stanford.edu/class/archive/cs/cs106b/cs106b.1158/styleguide.shtml
[#4]
<4> Объектно-ориентированное программирование:
https://ru.wikipedia.org/wiki
[#5]
<5> Можно ли использовать С++ вместо Си для небольших проектов в микроконтроллерах:
https://habr.com/post/347980/
<6> AsciiDoc шпаргалка: https://powerman.name/doc/asciidoc
<7> Reveal.js: https://github.com/hakimel/reveal.js#full-setup
<8> Asciidoctor Reveal.js: https://asciidoctor.org/docs/asciidoctor-revealjs/#node-javascript-setup
<9> Где хранятся ваши константы на микроконтроллере CortexM: https://habr.com/ru/post/453262/
<10>	Обзор одной российской RTOS, часть 4. Полезная теория: https://habr.com/post/337476/
<11> Начинаем изучать STM32: Что такое регистры? Как с ними работать? https://habr.com/ru/post/407083/
[#12]
<12> Справочное руководство на микроконтроллер STM32F411 https://www.st.com/resource/en/reference_manual/dm00119316.pdf
[#13]
<13> Безопасный доступ к полям регистров на С++ без ущерба эффективности (на примере CortexM) https://habr.com/ru/post/459642/
