== Введение
Данное методическое пособие предназначено для выполнения лабораторных работ с использованием
отладочных плат XNUCLEO F411RE для измерения физических величин на основе микроконтроллера STM32F411
с архитектурой Cortex-M4, операционной системы реального времени FreeRtos и языка программирования
С++ 14 интегрированной средой разработки IAR Embedded Workbench for ARM ver. 8.20

Методическое пособие написано в рамках курса “Программное обеспечение измерительных процессов”, но
оно будет полезным всем желающим освоить принципы разработки измерительных устройств на современных
микроконтроллерах.

Предполагается, что для изучения данного курса у студентов есть хорошие знания микропроцессорной
техники и навыки разработки ПО на языке С++ полученные на ранних курсах.

Методическое пособие состоит из 3 разделов. Первая часть ориентирована на создание проекта в IAR
Embedded Workbench,  работу с периферией микроконтроллера и возможности отладки системы IAR Embedded
Workbench, работе с детальной разработкой простых классов на языке UML в пакете starUML. Вторая
часть посвящена использованию прерываний, работе с операционной системой FreeRtos взаимодействию
между задачами. Заключительная часть ориентирована на принцип разработки архитектуры программного
обеспечения, шаблонам проектирования, разработки детальной архитектуры.

Модули связаны с курсовым проектированием в котором буду задействованы все части данного
методического пособия.

В 2017 году компания “Метран” безвозмездно предоставила ЮУрГУ на кафедру информационно-измерительная
техника 10 отладочных комплектов на базе микропроцессора Stm32F411RE на ядре Cortex M4 с различными
модулями расширения включающие в себя модули Bluetooth, WiFi, графическим индикатором, различными
сенсорами, включающие в себя датчики Холла, датчики влажности, температуры, звука, освещенности,
дыма, положения и многое другое. По этой причине курс ПОИП и лабораторный практикум выполняется
на отладочных платах XNUCLEO 411RE.

