== Предисловие

Специальность “Информационно-измерительная техника” направлена на создание и применение устройств и
систем, составляющих основу информационных технологий в различных отраслях промышленности.
Особое внимание должно уделяться компьютерной или микропроцессорной техники как со стороны
аппаратного, так и программного обеспечения.

В современном мире неотъемлемой частью практически любого измерительного устройства является
микроконтроллер. Важной особенностью применения микроконтроллеров в измерительных устройствах
является тот факт, что для надежной работы такого устройства необходимо не только надежная
аппаратура, но и качественное и надежное программное обеспечение управляющее микроконтроллером.
В настоящее время существует очень много методических пособий и книг по разработке устройств с
использованием микроконтроллеров, однако вопросы разработки программного обеспечения сводятся к
простым примерам на языке ассемблера и Си. Кроме того, существующие пособия значительно отстают от
быстроменяющихся изменений в микропроцессорной технике и тем более языках программирования.
Если еще недавно прорывом в программирование был выход стандарта С++11, то уже сегодня существует
стандарт С++20 и уже активна работа по стандарту С++23. Следует также заменить, что автором не
найдено ни одной книги или пособия, которые бы затрагивали, например, такие области разработки ПО
для микроконтроллеров, как архитектура программного обеспечения, использования UML и средств
моделирования архитектуры.

Предыдущие методические пособия для курса ПОИП, например,  <<#2>> были ориентированы на широкие области
применения информационных технологий, начиная от микроконтроллеров и заканчивая базами данных.
Однако по мнению автора, невозможно хорошо разобраться и усвоить столь большой объем разноплановой
информации. В итоге курс и лабораторные работы дают лишь поверхностное представление о разработке
программного обеспечения, а будущие инженеры не до конца усваивают материал и не могут детально
разобраться в принципах разработки программного обеспечения для измерительных устройств. Основываясь
на данном предубеждение, автором выбран иной путь, а именно более узкоспециализированное и
детальное рассмотрение принципов разработки программного обеспечения измерительных устройств на
базе современных микроконтроллеров.

Большую помощь в разработке методического материала оказал обучающийся на кафедре ИнИТ Загоскин Я.
Современные быстроизменяющиеся и эволюционирующие условия диктуют и новый подход к образованию, а
именно все больший упор делается на самообразование, самоусовершенствование и самостоятельный поиск
нужной информации с технической документации, системах поиска, книгах.

Поэтому довольно большая часть разделов предлагается студентам для самостоятельного изучения и
выполнения в качестве домашней практической работы.
Большое влияние на составление данного методического пособия оказал труд <<#1>> Недяка С.П., Шаропина
Ю.Б. откуда были заимствованы некоторые подходы и организационная структура методического пособия.
